# 데이터 초기화
CALL SP_RESET_TEST_DATA();

# 테스트 데이터 입력
CALL INPUT_DATA();

/* 장바구니 거치지 않고 구매 진행 테스트 시나리오 */

# 실물 상품 구매 시
# 1. 주문 생성

SELECT * FROM TBL_ORDERS; # 오더 테이블 확인 - 빈칸 확인

INSERT INTO TBL_ORDERS (
    ORDER_CD, USER_CD, PRODUCT_TYPE_CD, ORDER_TOTAL_PRICE_AMT
)
VALUES (
    5001, 1001, 1, 25000  -- PHYSICAL
);
SELECT VARIANT_STOCK_CNT FROM TBL_PRODUCT_VARIANTS; # 주문 상세 전 재고 확인
# 오더 테이블 확인 - 주문 확인. 오더 넘버 5001번
SELECT * FROM TBL_ORDERS;

# 2. 주문 상세 생성
SELECT * FROM TBL_ORDER_DETAILS; # 주문 상세 빈칸 확인

INSERT INTO TBL_ORDER_DETAILS (ORDER_CD, VARIANT_CD, ORD_DETL_QTY_CNT, ORD_DETL_PRICE_AMT)
VALUES (5001, 201, 1, 25000);  -- 실물 SIZE=L

SELECT * FROM TBL_ORDER_DETAILS; # 주문 상세 입력 확인

# 3. 재고 차감
# Trigger로 주문 상세가 생성 되면 재고 자동 차감
SELECT VARIANT_NM,VARIANT_STOCK_CNT FROM TBL_PRODUCT_VARIANTS; # SIZE=L 재고 1 차감확인

# 4. 배송 코드 생성
SELECT DELIVERY_PHY_CD,ST_PHY_CD,SHIPPING_CO_NM,TRACKING_NO FROM TBL_DELIVERY_PHY; # 배송 코드 빈칸 확인
INSERT INTO TBL_DELIVERY_PHY (DELIVERY_PHY_CD, ST_PHY_CD, SHIPPING_CO_NM, TRACKING_NO)
VALUES (7001, 1, NULL, NULL);  -- 초기 상태: 결제완료
SELECT DELIVERY_PHY_CD,ST_PHY_CD,SHIPPING_CO_NM,TRACKING_NO FROM TBL_DELIVERY_PHY; # 배송 코드 입력 확인

# 5. 배송 정보 저장
SELECT * FROM TBL_ORDER_PHY; # 배송정보 빈칸 확인
INSERT INTO TBL_ORDER_PHY (
    ORDER_CD, DELIVERY_PHY_CD, RECIPIENT_NM, RECIPIENT_TEL_NO,
    SHIPPING_UPYEON, SHIPPING_JUSO, SHIPPING_JUSO_D
)
VALUES (
    5001, 7001, '최테스터', '010-1234-5678',
    '6236', '서울특별시 강남구 테헤란로 123', '7층'
);
SELECT * FROM TBL_ORDER_PHY; # 배송정보 입력 확인

# 6. 주문 상태 이력 변경
SELECT * FROM TBL_ORDER_HISTORY; # 배송정보 빈칸 확인
INSERT INTO TBL_ORDER_HISTORY (ORD_HIST_CD, ORDER_CD, ORD_HIST_ST, ORD_HIST_REASON)
VALUES (9001, 5001, '결제완료', '바로구매 테스트');
SELECT * FROM TBL_ORDER_HISTORY; # 배송정보 입력 확인
