# 데이터 초기화
CALL SP_RESET_TEST_DATA();

# 테스트 데이터 입력
CALL INPUT_DATA();

/* 장바구니 거치지 않고 구매 진행 테스트 시나리오 */

# 기프티콘 구매 시
# 1. 주문 생성

SELECT * FROM TBL_ORDERS; # 오더 테이블 확인 - 빈칸 확인

INSERT INTO TBL_ORDERS (ORDER_CD, USER_CD, PRODUCT_TYPE_CD, ORDER_TOTAL_PRICE_AMT)
VALUES (5002, 1001, 2, 3000);  -- GIFTICON

SELECT * FROM TBL_PRODUCT_VARIANTS; # 주문 상세 전 재고 확인

SELECT * FROM TBL_ORDERS; # 오더 테이블 확인 - 주문 확인. 오더 넘버 5001번

# 2. 주문 상세 생성
SELECT * FROM TBL_ORDER_DETAILS; # 주문 상세 빈칸 확인

INSERT INTO TBL_ORDER_DETAILS (ORDER_CD, VARIANT_CD, ORD_DETL_QTY_CNT, ORD_DETL_PRICE_AMT)
VALUES (5002, 203, 1, 3000);

SELECT * FROM TBL_ORDER_DETAILS; # 주문 상세 입력 확인

# 3. 재고 차감
# 기프티콘이므로 재고 차감 안되야 함
SELECT VARIANT_NM,VARIANT_STOCK_CNT FROM TBL_PRODUCT_VARIANTS; # SIZE=REGULAR 재고 미차감 확인

# 4. 기프티콘 발송 코드 생성 ; 주문정보 테이블의 부모 테이블이라서 선행 생성
SELECT * FROM TBL_GFC_SEND; # 기프티콘 발송 정보 빈칸 확인

INSERT INTO TBL_GFC_SEND (GFC_SEND_CD,GFC_SEND_ST_CD, GFC_SEND_TYPE_CD)
VALUES (8001, 1,1 );

SELECT * FROM TBL_GFC_SEND; # 기프티콘 발송 정보 빈칸 확인

# 5. 기프티콘 주문 정보 저장
SELECT * FROM TBL_GFC_ORDER; # 기프티콘 주문 정보 빈칸 확인

INSERT INTO TBL_GFC_ORDER (ORDER_CD, GFC_SEND_CD, RECIPT_TEL)
VALUES (5002, 8001, '010-9876-5432');

SELECT * FROM TBL_GFC_ORDER; # 기프티콘 주문 정보 입력 확인

# 6. 주문 상태 이력 변경
SELECT * FROM TBL_ORDER_HISTORY; # 배송정보 빈칸 확인

INSERT INTO TBL_ORDER_HISTORY (ORD_HIST_CD, ORDER_CD, ORD_HIST_ST, ORD_HIST_REASON)
VALUES (9002, 5002, '결제완료', '바로구매 기프티콘 테스트');

SELECT * FROM TBL_ORDER_HISTORY; # 배송정보 입력 확인
